//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serialization.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Serialization.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IronPythonApplication1 {
            get {
                object obj = ResourceManager.GetObject("IronPythonApplication1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Program Files\IronPython 2.7\Lib.
        /// </summary>
        internal static string IronPythonLibPath {
            get {
                return ResourceManager.GetString("IronPythonLibPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IronPythonApplication1.py.
        /// </summary>
        internal static string PythonExecuteFile {
            get {
                return ResourceManager.GetString("PythonExecuteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # doc_title = «Я обізвуся до них…»
        ///# newdoc id = 0000
        ///# newpar id = 0001
        ///# sent_id = 0002
        ///# text = У домі римського патриція Руфіна була прегарна фреска, зображення Венери та Адоніса.
        ///# translit = U domi rymskoho patrycija Rufina bula preharna freska, zobrazennа Venery ta Adonisa.
        ///1	У	у	ADP	Spsl	Case=Loc	2	case	2:case	Id=0003|LTranslit=u|Translit=U
        ///2	домі	дім	NOUN	Ncmsln	Animacy=Inan|Case=Loc|Gender=Masc|Number=Sing	6	obl	6:obl	Id=0004|LTranslit=dim|Translit=domi
        ///3	римського	римський	ADJ	Ao-msgf	Cas [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Отладочный_текст {
            get {
                return ResourceManager.GetString("Отладочный_текст", resourceCulture);
            }
        }
    }
}
