/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Ufal.Parsito {

using System;
using System.Runtime.InteropServices;

public class Node : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Node(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(Node obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~Node() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          parsito_csharpPINVOKE.delete_Node(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public int id {
    set {
      parsito_csharpPINVOKE.Node_id_set(swigCPtr, value);
    } 
    get {
      int ret = parsito_csharpPINVOKE.Node_id_get(swigCPtr);
      return ret;
    } 
  }

  public string form {
    set {
      parsito_csharpPINVOKE.Node_form_set(swigCPtr, value);
      if (parsito_csharpPINVOKE.SWIGPendingException.Pending) throw parsito_csharpPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = parsito_csharpPINVOKE.Node_form_get(swigCPtr);
      if (parsito_csharpPINVOKE.SWIGPendingException.Pending) throw parsito_csharpPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string lemma {
    set {
      parsito_csharpPINVOKE.Node_lemma_set(swigCPtr, value);
      if (parsito_csharpPINVOKE.SWIGPendingException.Pending) throw parsito_csharpPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = parsito_csharpPINVOKE.Node_lemma_get(swigCPtr);
      if (parsito_csharpPINVOKE.SWIGPendingException.Pending) throw parsito_csharpPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string upostag {
    set {
      parsito_csharpPINVOKE.Node_upostag_set(swigCPtr, value);
      if (parsito_csharpPINVOKE.SWIGPendingException.Pending) throw parsito_csharpPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = parsito_csharpPINVOKE.Node_upostag_get(swigCPtr);
      if (parsito_csharpPINVOKE.SWIGPendingException.Pending) throw parsito_csharpPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string xpostag {
    set {
      parsito_csharpPINVOKE.Node_xpostag_set(swigCPtr, value);
      if (parsito_csharpPINVOKE.SWIGPendingException.Pending) throw parsito_csharpPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = parsito_csharpPINVOKE.Node_xpostag_get(swigCPtr);
      if (parsito_csharpPINVOKE.SWIGPendingException.Pending) throw parsito_csharpPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string feats {
    set {
      parsito_csharpPINVOKE.Node_feats_set(swigCPtr, value);
      if (parsito_csharpPINVOKE.SWIGPendingException.Pending) throw parsito_csharpPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = parsito_csharpPINVOKE.Node_feats_get(swigCPtr);
      if (parsito_csharpPINVOKE.SWIGPendingException.Pending) throw parsito_csharpPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public int head {
    set {
      parsito_csharpPINVOKE.Node_head_set(swigCPtr, value);
    } 
    get {
      int ret = parsito_csharpPINVOKE.Node_head_get(swigCPtr);
      return ret;
    } 
  }

  public string deprel {
    set {
      parsito_csharpPINVOKE.Node_deprel_set(swigCPtr, value);
      if (parsito_csharpPINVOKE.SWIGPendingException.Pending) throw parsito_csharpPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = parsito_csharpPINVOKE.Node_deprel_get(swigCPtr);
      if (parsito_csharpPINVOKE.SWIGPendingException.Pending) throw parsito_csharpPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string deps {
    set {
      parsito_csharpPINVOKE.Node_deps_set(swigCPtr, value);
      if (parsito_csharpPINVOKE.SWIGPendingException.Pending) throw parsito_csharpPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = parsito_csharpPINVOKE.Node_deps_get(swigCPtr);
      if (parsito_csharpPINVOKE.SWIGPendingException.Pending) throw parsito_csharpPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string misc {
    set {
      parsito_csharpPINVOKE.Node_misc_set(swigCPtr, value);
      if (parsito_csharpPINVOKE.SWIGPendingException.Pending) throw parsito_csharpPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = parsito_csharpPINVOKE.Node_misc_get(swigCPtr);
      if (parsito_csharpPINVOKE.SWIGPendingException.Pending) throw parsito_csharpPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public Children children {
    set {
      parsito_csharpPINVOKE.Node_children_set(swigCPtr, Children.getCPtr(value));
    } 
    get {
      IntPtr cPtr = parsito_csharpPINVOKE.Node_children_get(swigCPtr);
      Children ret = (cPtr == IntPtr.Zero) ? null : new Children(cPtr, false);
      return ret;
    } 
  }

  public Node(int id, string form) : this(parsito_csharpPINVOKE.new_Node__SWIG_0(id, form), true) {
    if (parsito_csharpPINVOKE.SWIGPendingException.Pending) throw parsito_csharpPINVOKE.SWIGPendingException.Retrieve();
  }

  public Node(int id) : this(parsito_csharpPINVOKE.new_Node__SWIG_1(id), true) {
  }

  public Node() : this(parsito_csharpPINVOKE.new_Node__SWIG_2(), true) {
  }

}

}
