/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Ufal.Parsito {

using System;
using System.Runtime.InteropServices;

public class TreeOutputFormat : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TreeOutputFormat(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(TreeOutputFormat obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~TreeOutputFormat() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          parsito_csharpPINVOKE.delete_TreeOutputFormat(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public virtual string writeTree(Tree t, TreeInputFormat additional_info) {
    string ret = parsito_csharpPINVOKE.TreeOutputFormat_writeTree__SWIG_0(swigCPtr, Tree.getCPtr(t), TreeInputFormat.getCPtr(additional_info));
    if (parsito_csharpPINVOKE.SWIGPendingException.Pending) throw parsito_csharpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual string writeTree(Tree t) {
    string ret = parsito_csharpPINVOKE.TreeOutputFormat_writeTree__SWIG_1(swigCPtr, Tree.getCPtr(t));
    if (parsito_csharpPINVOKE.SWIGPendingException.Pending) throw parsito_csharpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static TreeOutputFormat newOutputFormat(string name) {
    IntPtr cPtr = parsito_csharpPINVOKE.TreeOutputFormat_newOutputFormat(name);
    TreeOutputFormat ret = (cPtr == IntPtr.Zero) ? null : new TreeOutputFormat(cPtr, true);
    if (parsito_csharpPINVOKE.SWIGPendingException.Pending) throw parsito_csharpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static TreeOutputFormat newConlluOutputFormat() {
    IntPtr cPtr = parsito_csharpPINVOKE.TreeOutputFormat_newConlluOutputFormat();
    TreeOutputFormat ret = (cPtr == IntPtr.Zero) ? null : new TreeOutputFormat(cPtr, true);
    return ret;
  }

}

}
