/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Ufal.Parsito {

using System;
using System.Runtime.InteropServices;

public class TreeInputFormat : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TreeInputFormat(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(TreeInputFormat obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~TreeInputFormat() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          parsito_csharpPINVOKE.delete_TreeInputFormat(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public virtual void setText(string text) {
    parsito_csharpPINVOKE.TreeInputFormat_setText(swigCPtr, text);
  }

  public virtual bool nextTree(Tree t) {
    bool ret = parsito_csharpPINVOKE.TreeInputFormat_nextTree(swigCPtr, Tree.getCPtr(t));
    if (parsito_csharpPINVOKE.SWIGPendingException.Pending) throw parsito_csharpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string lastError() {
    string ret = parsito_csharpPINVOKE.TreeInputFormat_lastError(swigCPtr);
    return ret;
  }

  public static TreeInputFormat newInputFormat(string name) {
    IntPtr cPtr = parsito_csharpPINVOKE.TreeInputFormat_newInputFormat(name);
    TreeInputFormat ret = (cPtr == IntPtr.Zero) ? null : new TreeInputFormat(cPtr, true);
    if (parsito_csharpPINVOKE.SWIGPendingException.Pending) throw parsito_csharpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static TreeInputFormat newConlluInputFormat() {
    IntPtr cPtr = parsito_csharpPINVOKE.TreeInputFormat_newConlluInputFormat();
    TreeInputFormat ret = (cPtr == IntPtr.Zero) ? null : new TreeInputFormat(cPtr, true);
    return ret;
  }

}

}
